/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/

export const USER_AGREEMENT_FALLBACK_CONTENT = {
  en: `*Last updated: August 17, 2026*

Welcome to Next Router. This User Agreement (the “Agreement”) is entered into between you and **Next Router Team** (“we”, “us”, or “our”) and governs your access to and use of the Next Router website, account system, API gateway, developer tools, documentation, and related services (collectively, the “Service”). Please read this Agreement carefully before using the Service.

## 1. Acceptance and scope

By creating an account, accessing the website, calling an API endpoint, purchasing a service, or otherwise using Next Router, you confirm that you have read, understood, and agreed to this Agreement and our Privacy Policy. If you use the Service for an organization, you represent that you have authority to bind that organization, and “you” includes both you and that organization. If you do not agree, do not use the Service.

## 2. Eligibility and accounts

You must have the legal capacity required by applicable law to enter into this Agreement. You must provide accurate, current, and complete registration information and keep it updated. You are responsible for protecting your password, API keys, access tokens, passkeys, and other credentials, as well as for all activity performed through your account. Do not share credentials publicly or allow unauthorized persons to use them. Notify us promptly at [help@nextrouter.cc](mailto:help@nextrouter.cc) if you suspect unauthorized access or a security incident.

## 3. Description of the Service

Next Router provides technical access, routing, management, metering, and related capabilities for artificial-intelligence services supplied by us or by third-party providers. Available models, routes, prices, rate limits, context limits, response times, and features may vary by provider, region, account, and time. Unless expressly stated otherwise, Next Router does not own or control third-party models and does not guarantee that any particular model or provider will remain available.

## 4. Acceptable use

You may use the Service only for lawful purposes and in accordance with this Agreement, applicable laws, and any rules shown in the Service. You must not use the Service to create, transmit, store, or facilitate unlawful, fraudulent, deceptive, infringing, abusive, harassing, hateful, sexually exploitative, malicious, or privacy-invasive content. You must not attack, probe, disrupt, overload, reverse engineer, bypass limits or security controls, scrape protected areas, distribute malware, impersonate another person, misuse payment mechanisms, resell access without permission, or use automated methods that materially impair the Service or other users.

You are responsible for your prompts, files, instructions, outputs, integrations, and downstream use. You must obtain all permissions needed for any data you submit and must not submit secrets, regulated data, or personal information unless you are legally entitled to do so and have assessed whether the selected provider is appropriate.

## 5. AI outputs and third-party services

AI-generated content can be inaccurate, incomplete, outdated, offensive, or unsuitable for your purpose. You must independently review outputs before relying on or publishing them, especially for medical, legal, financial, employment, safety-critical, or other high-impact decisions. The Service is not a substitute for qualified professional advice.

Requests may be processed by third-party AI providers and infrastructure vendors. Their terms, content rules, availability, and privacy practices may also apply. You are responsible for reviewing and complying with those requirements. We are not responsible for third-party services, websites, models, or content that we do not control.

## 6. Fees, quotas, and billing

Some features require payment or consume account quota. Prices, exchange ratios, billing units, and promotional credits are displayed in the Service or agreed separately. You authorize us and our payment providers to process applicable charges. Usage records generated by the Service will be the primary basis for billing, subject to correction of clear technical errors. Unless required by law or expressly stated otherwise, consumed usage and promotional credits are non-refundable and promotional credits have no cash value. You are responsible for applicable taxes, bank charges, and keeping sufficient balance for continued use.

## 7. Intellectual property

Next Router Team and its licensors retain all rights in the Service, including its interface, software, design, documentation, trademarks, and related materials, except for rights expressly granted to you. Subject to this Agreement, we grant you a limited, non-exclusive, non-transferable, revocable right to use the Service for its intended purpose. You retain rights you lawfully hold in content you submit. You grant us the limited rights necessary to host, transmit, process, and route that content solely to operate, secure, and support the Service.

## 8. Availability, changes, and beta features

We work to keep the Service reliable but do not promise uninterrupted or error-free operation. Maintenance, provider outages, network failures, security events, legal requirements, or circumstances beyond our reasonable control may delay, limit, or interrupt access. We may add, modify, suspend, or discontinue features, models, routes, limits, or pricing. When reasonably practicable, we will provide notice of material changes. Beta or preview features may be changed or withdrawn at any time and are provided for evaluation.

## 9. Suspension and termination

We may restrict, suspend, or terminate access when reasonably necessary to protect users or the Service, respond to security or legal risks, address unpaid charges, investigate suspected abuse, or enforce this Agreement. You may stop using the Service at any time. Termination does not eliminate obligations or liabilities that arose before termination, including payment obligations. Provisions that by their nature should survive will remain effective.

## 10. Disclaimers and limitation of liability

To the maximum extent permitted by law, the Service is provided “as is” and “as available”. Next Router Team disclaims implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, and uninterrupted availability. We do not guarantee any AI output, provider result, commercial outcome, data recovery, or compatibility with your systems.

To the maximum extent permitted by law, Next Router Team will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, revenue, data, goodwill, business opportunities, or service interruption arising from or related to the Service. Nothing in this Agreement excludes liability that cannot lawfully be excluded or limited.

## 11. Changes to this Agreement

We may update this Agreement to reflect changes in the Service, law, security practices, or business operations. The updated version will be posted on this page with a revised date. If a change materially affects your rights, we will take reasonable steps to provide additional notice. Continuing to use the Service after the updated Agreement becomes effective constitutes acceptance of the revised terms.

## 12. Contact

Questions, complaints, account issues, or legal notices concerning this Agreement may be sent to **Next Router Team** at [help@nextrouter.cc](mailto:help@nextrouter.cc). We will review legitimate requests and respond within a reasonable period.`,
  zh: `*最后更新：2026 年 8 月 17 日*

欢迎使用 Next Router。本用户协议（以下简称“本协议”）由您与 **Next Router Team**（以下简称“我们”）共同订立，适用于您访问和使用 Next Router 网站、账户系统、API 网关、开发者工具、文档及相关服务（以下统称“本服务”）的行为。使用本服务前，请您认真阅读并充分理解本协议。

## 1. 协议接受与适用范围

当您创建账户、访问网站、调用 API、购买服务或以其他方式使用 Next Router 时，即表示您已阅读、理解并同意遵守本协议及隐私政策。如果您代表组织使用本服务，您确认自己有权使该组织受本协议约束，此时“您”同时包括您本人及该组织。如您不同意本协议，请勿使用本服务。

## 2. 使用资格与账户安全

您应具备适用法律要求的民事行为能力，并提供真实、准确、完整且持续有效的注册信息。您有责任妥善保管密码、API 密钥、访问令牌、通行密钥及其他凭据，并对通过您账户发生的全部活动负责。请勿公开分享凭据或允许未经授权的人员使用。若您发现账户被未授权访问或发生安全事件，请立即通过 [help@nextrouter.cc](mailto:help@nextrouter.cc) 联系我们。

## 3. 服务说明

Next Router 为我们或第三方提供的人工智能服务提供技术接入、请求路由、管理、计量及相关能力。可用模型、线路、价格、速率限制、上下文限制、响应时间和功能可能因供应商、地区、账户及时间而变化。除非另有明确说明，Next Router 不拥有或控制第三方模型，也不保证任何特定模型或供应商持续可用。

## 4. 合理使用规则

您仅可在合法目的下，依照本协议、适用法律及本服务页面展示的规则使用本服务。您不得利用本服务创建、传输、存储或协助传播违法、欺诈、欺骗、侵权、辱骂、骚扰、仇恨、性剥削、恶意或侵犯隐私的内容；不得攻击、探测、干扰或过载本服务，不得反向工程、绕过配额或安全控制、抓取受保护区域、传播恶意软件、冒充他人、滥用支付机制、未经许可转售服务，或以自动化方式严重影响本服务及其他用户的正常使用。

您应对提交的提示词、文件、指令、生成结果、集成方式及后续使用承担责任。您必须取得提交任何数据所需的全部授权；除非您有合法处理依据并已确认所选服务供应商适合处理相关数据，否则请勿提交密码、商业秘密、受监管数据或个人信息。

## 5. 人工智能输出与第三方服务

人工智能生成内容可能存在错误、不完整、过时、冒犯性或不适用于特定目的等情况。您在依赖、使用或发布输出前应进行独立审查，特别是在医疗、法律、金融、就业、安全关键或其他高影响场景中。本服务不能替代具备资质的专业意见。

您的请求可能由第三方人工智能供应商及基础设施服务商处理，其服务条款、内容规则、可用性和隐私政策也可能适用。您有责任了解并遵守相关要求。对于我们无法控制的第三方服务、网站、模型或内容，我们不承担责任。

## 6. 费用、额度与结算

部分功能需要付费或消耗账户额度。价格、兑换比例、计费单位及活动赠送额度以本服务页面展示或双方另行约定的内容为准。您授权我们及支付服务商处理相应费用。本服务生成的使用记录是计费的主要依据，但明显的技术错误可依法或依规则更正。除法律另有要求或页面另有明确说明外，已消耗的用量和活动赠送额度不予退还，赠送额度不可兑换现金。您应承担适用税费、银行手续费，并保持充足余额以持续使用服务。

## 7. 知识产权

除明确授予您的权利外，Next Router Team 及其许可方保留本服务及其界面、软件、设计、文档、商标和相关材料的全部权利。在您遵守本协议的前提下，我们授予您一项有限的、非独占的、不可转让的、可撤销的使用权，仅限按照本服务预定用途使用。您保留对自己依法拥有的输入内容的权利，并授权我们在运营、保护和支持本服务所必需的范围内托管、传输、处理和路由相关内容。

## 8. 服务可用性、变更与测试功能

我们会努力保持服务稳定，但不承诺本服务始终不中断或完全无错误。维护、供应商故障、网络异常、安全事件、法律要求或其他超出合理控制范围的情形，均可能导致访问延迟、受限或中断。我们可能新增、调整、暂停或停止部分功能、模型、线路、限制或价格，并将在合理可行时对重大变化进行通知。测试版或预览功能仅供评估，可能随时变更或撤回。

## 9. 限制、暂停与终止

为保护用户或本服务、应对安全或法律风险、处理未付款项、调查疑似滥用行为或执行本协议，我们可在合理必要时限制、暂停或终止您的访问。您可以随时停止使用本服务。服务终止不影响终止前已经产生的义务或责任，包括付款义务；按照其性质应继续有效的条款，在终止后仍然有效。

## 10. 免责声明与责任限制

在法律允许的最大范围内，本服务按“现状”和“可用”状态提供。Next Router Team 不作适销性、特定用途适用性、不侵权、准确性或持续可用性等默示保证，也不保证任何人工智能输出、供应商结果、商业效果、数据恢复结果或与您系统的兼容性。

在法律允许的最大范围内，对于因本服务引起或与本服务有关的间接、附带、特殊、后果性、惩罚性损失，以及利润、收入、数据、商誉、商业机会损失或服务中断，Next Router Team 不承担责任。本协议不排除或限制依法不得排除或限制的责任。

## 11. 协议变更

我们可能根据服务、法律、安全措施或业务运营的变化更新本协议。更新后的版本将在本页面发布并标注新的更新日期。若变更对您的权利产生重大影响，我们会采取合理方式另行提示。更新后的协议生效后，您继续使用本服务即视为接受修订后的条款。

## 12. 联系我们

如对本协议有任何疑问、投诉、账户问题或需发送法律通知，请通过 [help@nextrouter.cc](mailto:help@nextrouter.cc) 联系 **Next Router Team**。我们会审核合理、真实的请求，并在合理期限内回复。`,
} as const

export const PRIVACY_POLICY_FALLBACK_CONTENT = {
  en: `*Last updated: August 17, 2026*

This Privacy Policy explains how **Next Router Team** (“we”, “us”, or “our”) collects, uses, stores, shares, and protects information when you visit Next Router, create an account, use our API gateway, contact support, or otherwise interact with our website, applications, documentation, and related services (collectively, the “Service”).

## 1. Scope and responsibility

This Privacy Policy applies to information processed by Next Router Team in connection with the Service. Third-party AI providers, payment processors, identity providers, hosting vendors, and websites may process information under their own privacy policies. We encourage you to review those policies before selecting or using a third-party service through Next Router.

## 2. Information we collect

Depending on how you use the Service, we may collect the following categories of information:

- **Account and contact information:** username, email address, account identifier, authentication status, profile settings, organization information, and support contact details.
- **Authentication and security information:** password hashes, API key identifiers, access tokens, passkey metadata, sign-in history, security events, and anti-abuse signals. We do not need your plaintext password to operate the Service.
- **Usage and transaction information:** API route, selected model, request time, token or unit counts, quota changes, billing records, subscription status, payment status, error codes, latency, and operational metrics.
- **Request and response data:** prompts, messages, files, images, audio, model parameters, generated outputs, and related metadata when needed to route or provide a request. The exact processing and retention of content may depend on your settings, the selected model, and the relevant upstream provider.
- **Device and log information:** IP address, browser type, operating system, device characteristics, language, referring page, timestamps, cookie identifiers, and server or application logs.
- **Communications:** information you include in support requests, emails, feedback, abuse reports, or other communications with Next Router Team.

Please avoid submitting personal information or confidential data that is not necessary for your use of the Service.

## 3. How we use information

We use information to provide, route, maintain, and improve the Service; create and secure accounts; authenticate users and API requests; calculate usage, quotas, and charges; process payments; diagnose errors; provide customer support; communicate service and security notices; prevent fraud, abuse, and unauthorized access; enforce agreements; comply with legal obligations; and protect the rights, safety, and integrity of users, Next Router Team, and the public.

Where applicable law requires a legal basis, we process information as necessary to perform our agreement with you, comply with legal obligations, pursue legitimate interests such as security and service improvement, or act with your consent. You may withdraw consent where consent is the applicable basis, without affecting earlier lawful processing.

## 4. AI request processing

To complete an API request, Next Router may transmit request content and technical metadata to the model or infrastructure provider you select or that is selected by the configured route. Those providers may process data in different locations and under different terms. Do not send secrets, regulated information, or sensitive personal data unless you have authority to do so and have verified that the selected route and provider meet your requirements.

We may process limited request or response information for routing, abuse prevention, debugging, accounting, and support. Retention behavior may vary based on administrator settings, operational needs, and legal requirements. Enterprise or separately contracted arrangements may include different data-handling terms.

## 5. Cookies and similar technologies

We may use local storage, cookies, or similar technologies to maintain sessions, remember language and theme preferences, protect sign-in flows, measure reliability, and prevent abuse. Some technologies are necessary for the Service to function. You can control cookies through your browser, but disabling required storage may prevent sign-in or cause features to stop working correctly.

## 6. How we share information

We do **not sell personal information**. We may share information only as reasonably necessary with:

- AI model and infrastructure providers used to fulfill your requests;
- hosting, storage, monitoring, email, customer-support, identity, security, analytics, and payment service providers acting on our behalf;
- an organization administrator when your account is managed by that organization;
- professional advisers, auditors, insurers, or transaction counterparties subject to appropriate confidentiality obligations;
- authorities or other parties when required by law, legal process, or a good-faith need to protect rights, safety, security, users, or the Service; and
- a successor in a merger, financing, reorganization, acquisition, or transfer of all or part of the Service, subject to applicable law.

Service providers are expected to process information for the services they provide and to apply appropriate safeguards.

## 7. International data transfers

Next Router and its providers may process information in countries or regions other than where you live. Privacy laws in those locations may differ. Where required, we use reasonable legal and contractual safeguards for cross-border transfers. Your selection of a particular model or provider may influence where request data is processed.

## 8. Data retention

We retain information only for as long as reasonably necessary to provide and secure the Service, maintain accurate transaction and accounting records, resolve disputes, enforce agreements, meet legal obligations, and protect against fraud or abuse. Retention periods vary by data type, account status, configuration, and legal requirement. We may retain aggregated or de-identified information where it can no longer reasonably identify you.

## 9. Security

We use reasonable administrative, technical, and organizational measures designed to protect information from unauthorized access, alteration, disclosure, or destruction. No internet transmission or storage system is completely secure, so we cannot guarantee absolute security. You are responsible for using strong credentials, protecting API keys, limiting permissions, and promptly reporting suspected compromise to [help@nextrouter.cc](mailto:help@nextrouter.cc).

## 10. Your rights and choices

Depending on your location, you may have rights to request access to, correction of, deletion of, restriction of, or portability of certain personal information, or to object to certain processing. You may also be entitled to lodge a complaint with a local privacy authority. We may need to verify your identity and may retain information when permitted or required by law. To submit a privacy request, email [help@nextrouter.cc](mailto:help@nextrouter.cc) with enough detail for us to understand and evaluate the request.

You can update certain account information through the Service, manage browser storage through browser settings, and unsubscribe from optional communications using the instructions in those messages. Essential security, billing, and service notices cannot always be disabled while an account remains active.

## 11. Children

The Service is not directed to children who are below the minimum age required to consent to online services in their jurisdiction. We do not knowingly collect personal information from such children without appropriate authorization. If you believe a child has provided information improperly, contact us so we can investigate and take appropriate action.

## 12. Changes to this Privacy Policy

We may update this Privacy Policy to reflect changes in the Service, law, technology, or our data practices. The revised version will be posted on this page with an updated date. When a change is material, we will take reasonable steps to provide additional notice. Your continued use of the Service after the effective date is subject to the updated policy.

## 13. Contact us

For privacy questions, data requests, complaints, or security concerns, contact **Next Router Team** at [help@nextrouter.cc](mailto:help@nextrouter.cc). Please do not include passwords, API keys, or unnecessary sensitive information in your email.`,
  zh: `*最后更新：2026 年 8 月 17 日*

本隐私政策说明 **Next Router Team**（以下简称“我们”）在您访问 Next Router、创建账户、使用 API 网关、联系客户支持，或以其他方式使用我们的网站、应用、文档及相关服务（以下统称“本服务”）时，如何收集、使用、存储、共享和保护相关信息。

## 1. 适用范围与责任

本隐私政策适用于 Next Router Team 因提供本服务而处理的信息。第三方人工智能供应商、支付机构、身份认证服务商、托管服务商及外部网站可能依照其各自的隐私政策处理信息。通过 Next Router 选择或使用第三方服务前，我们建议您仔细阅读相关政策。

## 2. 我们收集的信息

根据您使用本服务的方式，我们可能收集以下类别的信息：

- **账户与联系信息：** 用户名、电子邮箱、账户标识、认证状态、个人设置、组织信息及客户支持联系方式。
- **认证与安全信息：** 密码哈希值、API 密钥标识、访问令牌、通行密钥元数据、登录历史、安全事件和反滥用信号。运营本服务不需要获取您的明文密码。
- **使用与交易信息：** API 线路、所选模型、请求时间、令牌或计费单位数量、额度变化、账单记录、订阅状态、支付状态、错误代码、延迟和运行指标。
- **请求与响应数据：** 为完成请求而处理的提示词、消息、文件、图片、音频、模型参数、生成结果及相关元数据。内容的具体处理和保留方式可能取决于您的设置、所选模型及对应的上游供应商。
- **设备与日志信息：** IP 地址、浏览器类型、操作系统、设备特征、语言、来源页面、时间戳、Cookie 标识及服务器或应用日志。
- **沟通信息：** 您在支持请求、电子邮件、意见反馈、滥用举报或其他与 Next Router Team 的沟通中提供的信息。

请勿提交使用本服务并不需要的个人信息或机密数据。

## 3. 我们如何使用信息

我们使用相关信息来提供、路由、维护及改进本服务；创建和保护账户；验证用户及 API 请求；计算用量、额度与费用；处理支付；诊断错误；提供客户支持；发送服务与安全通知；防范欺诈、滥用及未经授权的访问；执行相关协议；履行法律义务；以及保护用户、Next Router Team 和公众的权利、安全与服务完整性。

在适用法律要求说明处理依据的情况下，我们会基于履行与您的协议、遵守法律义务、实现安全及服务改进等合法利益，或基于您的同意处理信息。当处理依据为同意时，您可以撤回同意，但不影响撤回前已经进行的合法处理。

## 4. 人工智能请求处理

为完成 API 请求，Next Router 可能将请求内容和必要的技术元数据发送给您选择的模型供应商，或由已配置线路选定的模型及基础设施供应商。不同供应商可能在不同国家或地区处理数据，并适用不同条款。除非您有权提交相关信息并已确认所选线路和供应商满足您的要求，否则请勿发送密码、商业秘密、受监管信息或敏感个人信息。

为实现路由、滥用防范、故障排查、计费和客户支持，我们可能处理有限的请求或响应信息。信息保留方式可能因管理员设置、运营需要和法律要求而变化。企业客户或另行签署协议的安排可能适用不同的数据处理条款。

## 5. Cookie 与类似技术

我们可能使用本地存储、Cookie 或类似技术来维持会话、记住语言及主题偏好、保护登录流程、衡量服务可靠性并防止滥用。其中部分技术是本服务正常运行所必需的。您可以通过浏览器管理 Cookie，但禁用必要存储可能导致无法登录或部分功能无法正常使用。

## 6. 我们如何共享信息

我们**不会出售个人信息**。仅在合理必要的范围内，我们可能与以下主体共享信息：

- 为完成您的请求而使用的人工智能模型及基础设施供应商；
- 代表我们提供托管、存储、监控、邮件、客户支持、身份认证、安全、分析或支付服务的供应商；
- 当您的账户由组织管理时，该组织的管理员；
- 负有适当保密义务的专业顾问、审计机构、保险机构或交易相关方；
- 在法律、司法程序要求，或为善意保护权利、人身安全、系统安全、用户及本服务所必需时，有关主管部门或其他主体；以及
- 在合并、融资、重组、收购或转让本服务全部或部分业务时的继受主体，但应遵守适用法律。

我们要求服务供应商仅为提供相关服务处理信息，并采取适当的保护措施。

## 7. 跨境数据传输

Next Router 及其服务供应商可能在您所在国家或地区以外处理信息，当地隐私法律可能与您所在地不同。在法律要求的情况下，我们会为跨境传输采取合理的法律及合同保障措施。您选择的特定模型或供应商可能影响请求数据的实际处理地点。

## 8. 信息保留

我们仅在提供和保护本服务、保存准确的交易及会计记录、解决争议、执行协议、履行法律义务以及防范欺诈或滥用所合理必要的期限内保留信息。具体期限会因数据类型、账户状态、系统配置和法律要求而不同。对于已无法合理识别到您的汇总信息或去标识化信息，我们可能继续保留和使用。

## 9. 信息安全

我们采取合理的管理、技术和组织措施，力求防止信息遭到未经授权的访问、篡改、披露或销毁。但任何互联网传输或存储系统均无法保证绝对安全。您有责任使用高强度凭据、妥善保管 API 密钥、限制权限，并在发现疑似泄露时立即通过 [help@nextrouter.cc](mailto:help@nextrouter.cc) 联系我们。

## 10. 您的权利与选择

根据您所在地区的法律，您可能有权请求访问、更正、删除、限制处理或获取部分个人信息的副本，也可能有权反对某些处理并向当地隐私监管机构投诉。我们可能需要核验您的身份，并可能在法律允许或要求时保留部分信息。如需提交隐私请求，请发送邮件至 [help@nextrouter.cc](mailto:help@nextrouter.cc)，并提供足够信息以便我们理解和评估您的请求。

您可以通过本服务更新部分账户信息，通过浏览器设置管理本地存储，并按照邮件中的说明退订可选通知。当账户仍处于有效状态时，必要的安全、计费和服务通知可能无法关闭。

## 11. 未成年人

本服务不面向未达到其所在司法辖区网络服务同意最低年龄的未成年人。未经适当授权，我们不会故意收集此类未成年人的个人信息。如果您认为未成年人不当提供了信息，请联系我们，我们将进行调查并采取适当措施。

## 12. 隐私政策变更

我们可能根据服务、法律、技术或数据处理实践的变化更新本隐私政策。修订后的版本会在本页面发布并标注新的更新日期。若变更较为重大，我们会采取合理方式另行提示。修订版本生效后，您继续使用本服务将适用更新后的政策。

## 13. 联系我们

如有隐私问题、数据请求、投诉或安全疑虑，请通过 [help@nextrouter.cc](mailto:help@nextrouter.cc) 联系 **Next Router Team**。请勿在邮件中包含密码、API 密钥或不必要的敏感信息。`,
} as const
